const contactData = [
  {
    contactType: 'person',
    firstName: 'Abi',
    id: '103',
    imageAvailable: false,
    lastName: 'Azmi',
    lookupKey: '419i6f464dcf89ec7f67',
    middleName: 'Zul',
    name: 'Abi Zul Azmi',
    phoneNumbers: [
      {
        id: '527',
        isPrimary: 0,
        label: 'unknown',
        number: '+6285380048569',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Abimanyu',
    id: '10',
    imageAvailable: false,
    lastName: 'Pangestu',
    lookupKey: '419i5683023609a26683',
    name: 'Abimanyu Pangestu',
    phoneNumbers: [
      {
        id: '50',
        isPrimary: 1,
        label: 'mobile',
        number: '089698109583',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Adi',
    id: '122',
    imageAvailable: false,
    lastName: 'Saputra',
    lookupKey: '419i7a4a806c8d4f61f6.419i56a735b89cfe3bf',
    name: 'Adi Saputra',
    phoneNumbers: [
      {
        id: '622',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 822-8192-1607',
        type: '2',
      },
      {
        id: '627',
        isPrimary: 0,
        label: 'unknown',
        number: '+6282281921607',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'ADSI',
    id: '218',
    imageAvailable: false,
    lastName: 'Radhit',
    lookupKey: '419i6e1429e108f31860.3789r218-2A304E3A4C2A30383A50',
    name: 'ADSI Radhit',
    phoneNumbers: [
      {
        id: '297',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 822-1112-5103',
        type: '2',
      },
      {
        id: '1114',
        isPrimary: 0,
        label: 'mobile',
        number: '+6282211125103',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'ADSI',
    id: '300',
    imageAvailable: false,
    lastName: 'Egi',
    lookupKey: '419i38b71fe008dfd7ff.3789r300-2A304E3A32363A',
    name: 'ADSI Egi',
    phoneNumbers: [
      {
        id: '482',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 817-121-887',
        type: '2',
      },
      {
        id: '1524',
        isPrimary: 0,
        label: 'mobile',
        number: '+62817121887',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Agun',
    id: '222',
    imageAvailable: false,
    lastName: 'Mardian',
    lookupKey:
      '419i7f8c777b8ff728ff.419i787dcd1908a901cb.3789r222-2A365244422A4C303A2A44',
    name: 'Agun Mardian',
    phoneNumbers: [
      {
        id: '632',
        isPrimary: 0,
        label: 'unknown',
        number: '+6285382499026',
      },
      {
        id: '637',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 853-8249-9026',
        type: '2',
      },
      {
        data3: 'WhatsApp',
        id: '1134',
        isPrimary: 0,
        label: 'WhatsApp',
        number: '+6285382499026',
        type: '0',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Agung',
    id: '276',
    imageAvailable: false,
    lastName: 'Sutrisno',
    lookupKey:
      '419i4f2d004c88874d78.3789r276-2A365244363C46443A4E52504C3A4E4446',
    middleName: 'Joni',
    name: 'Agung Joni Sutrisno',
    phoneNumbers: [
      {
        id: '174',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 812-7960-7359',
        type: '2',
      },
      {
        id: '1404',
        isPrimary: 0,
        label: 'mobile',
        number: '+6281279607359',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Agung',
    id: '126',
    imageAvailable: false,
    lastName: 'Kartiko',
    lookupKey: '419i7ddf63408b3af4ef.419i4834be2d88377bd3',
    name: 'Agung Kartiko',
    phoneNumbers: [
      {
        id: '642',
        isPrimary: 0,
        label: 'unknown',
        number: '+6285783160012',
      },
      {
        id: '647',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 856-6937-7963',
        type: '2',
      },
      {
        id: '648',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 857-8316-0012',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Agung',
    id: '217',
    imageAvailable: false,
    lastName: 'Permana',
    lookupKey:
      '419i7d075fb60b53345b.419i7601622b08ca36e5.3789r217-2A3652443648324C422A442A',
    name: 'Agung Permana',
    phoneNumbers: [
      {
        id: '653',
        isPrimary: 0,
        label: 'unknown',
        number: '+6285609396550',
      },
      {
        id: '658',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 856-0939-6550',
        type: '2',
      },
      {
        id: '1109',
        isPrimary: 0,
        label: 'mobile',
        number: '+6285609396550',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    emails: [
      {
        email: 'albarpratama47@gmail.com',
        id: '863',
        isPrimary: 1,
        label: 'home',
        type: '1',
      },
    ],
    firstName: 'Albar',
    id: '169',
    image: {
      uri: 'content://com.android.contacts/contacts/169/photo',
    },
    imageAvailable: true,
    lookupKey: '419i5aca2544970581c7',
    name: 'Albar',
  },
  {
    contactType: 'person',
    firstName: 'Albar Pratama',
    id: '405',
    imageAvailable: false,
    lastName: 'Tanjung',
    lookupKey:
      '419id74bb8b0965c5fe.3789r194-2A402C2A4C484C2A502A422A4852504C2A502A443C524436.3789r404-2A402C2A4C484C2A502A422A4852504C2A502A443C524436',
    middleName: 'Putra',
    name: 'Albar Pratama Putra Tanjung',
    phoneNumbers: [
      {
        id: '319',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 858-3236-2547',
        type: '2',
      },
      {
        id: '320',
        isPrimary: 0,
        label: 'mobile',
        number: '+62895359414183',
        type: '2',
      },
      {
        id: '321',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 822-5143-5530',
        type: '2',
      },
      {
        id: '994',
        isPrimary: 0,
        label: 'mobile',
        number: '+6282251435530',
        type: '2',
      },
      {
        id: '1901',
        isPrimary: 0,
        label: 'mobile',
        number: '+62895359414183',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Amar',
    id: '240',
    imageAvailable: false,
    lookupKey: '419i7920179f0aa1a0f7.3789r240-2A422A4C',
    name: 'Amar',
    phoneNumbers: [
      {
        id: '45',
        isPrimary: 1,
        label: 'mobile',
        number: '082269998953',
        type: '2',
      },
      {
        id: '1224',
        isPrimary: 0,
        label: 'mobile',
        number: '082269998953',
        type: '2',
      },
    ],
  },
  {
    contactType: 'person',
    firstName: 'Amar',
    id: '145',
    imageAvailable: false,
    lastName: 'Ruli',
    lookupKey: '419i9ab54278b31aa34',
    name: 'Amar Ruli',
    phoneNumbers: [
      {
        id: '739',
        isPrimary: 0,
        label: 'mobile',
        number: '+62 896-2844-8978',
        type: '2',
      },
    ],
  },
];

const calendarData = [
  {
    accessLevel: 'owner',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert'],
    allowsModifications: false,
    color: '#000000',
    id: '1',
    isPrimary: false,
    isSynced: true,
    isVisible: true,
    name: null,
    ownerAccount: 'local account',
    source: {
      isLocalAccount: true,
      name: 'local account',
      type: 'LOCAL',
    },
    timeZone: null,
    title: 'local account',
  },
  {
    accessLevel: 'read',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert', 'email'],
    allowsModifications: false,
    color: '#9A9CFF',
    id: '2',
    isPrimary: false,
    isSynced: true,
    isVisible: true,
    name: 'Holidays in Indonesia',
    ownerAccount: 'en.indonesian#holiday@group.v.calendar.google.com',
    source: {
      isLocalAccount: false,
      name: 'mrandi96@gmail.com',
      type: 'com.google',
    },
    timeZone: 'Asia/Jakarta',
    title: 'Holidays in Indonesia',
  },
  {
    accessLevel: 'read',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert', 'email'],
    allowsModifications: false,
    color: '#92E1C0',
    id: '3',
    isPrimary: false,
    isSynced: false,
    isVisible: false,
    name: 'Birthdays',
    ownerAccount: 'addressbook#contacts@group.v.calendar.google.com',
    source: {
      isLocalAccount: false,
      name: 'mrandi96@gmail.com',
      type: 'com.google',
    },
    timeZone: 'Asia/Jakarta',
    title: 'Birthdays',
  },
  {
    accessLevel: 'read',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert', 'email'],
    allowsModifications: false,
    color: '#16A765',
    id: '4',
    isPrimary: false,
    isSynced: true,
    isVisible: true,
    name: 'Hari libur di Indonesia',
    ownerAccount: 'id.indonesian#holiday@group.v.calendar.google.com',
    source: {
      isLocalAccount: false,
      name: 'mrandi96@gmail.com',
      type: 'com.google',
    },
    timeZone: 'Asia/Jakarta',
    title: 'Hari libur di Indonesia',
  },
  {
    accessLevel: 'owner',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert', 'email'],
    allowsModifications: false,
    color: '#9FE1E7',
    id: '5',
    isPrimary: false,
    isSynced: true,
    isVisible: true,
    name: 'mrandi96@gmail.com',
    ownerAccount: 'mrandi96@gmail.com',
    source: {
      isLocalAccount: false,
      name: 'mrandi96@gmail.com',
      type: 'com.google',
    },
    timeZone: 'Asia/Jakarta',
    title: 'mrandi96@gmail.com',
  },
  {
    accessLevel: 'read',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert', 'email'],
    allowsModifications: false,
    color: '#92E1C0',
    id: '6',
    isPrimary: false,
    isSynced: false,
    isVisible: false,
    name: 'Birthdays',
    ownerAccount: 'addressbook#contacts@group.v.calendar.google.com',
    source: {
      isLocalAccount: false,
      name: '2019mrandi@gmail.com',
      type: 'com.google',
    },
    timeZone: 'UTC',
    title: 'Birthdays',
  },
  {
    accessLevel: 'read',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert', 'email'],
    allowsModifications: false,
    color: '#16A765',
    id: '7',
    isPrimary: false,
    isSynced: false,
    isVisible: false,
    name: 'Holidays in Indonesia',
    ownerAccount: 'en.indonesian#holiday@group.v.calendar.google.com',
    source: {
      isLocalAccount: false,
      name: '2019mrandi@gmail.com',
      type: 'com.google',
    },
    timeZone: 'UTC',
    title: 'Holidays in Indonesia',
  },
  {
    accessLevel: 'owner',
    allowedAttendeeTypes: ['none', 'required', 'optional'],
    allowedAvailabilities: ['busy', 'free'],
    allowedReminders: ['default', 'alert', 'email'],
    allowsModifications: false,
    color: '#9FE1E7',
    id: '8',
    isPrimary: false,
    isSynced: true,
    isVisible: true,
    name: '2019mrandi@gmail.com',
    ownerAccount: '2019mrandi@gmail.com',
    source: {
      isLocalAccount: false,
      name: '2019mrandi@gmail.com',
      type: 'com.google',
    },
    timeZone: 'UTC',
    title: '2019mrandi@gmail.com',
  },
];

export { contactData, calendarData };
